/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IHealthConsent__factory } from './IHealthConsent__factory.js';
export { MedicalRecords__factory } from './MedicalRecords__factory.js';