/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */


import { ethers } from 'ethers'
import { DeployContractOptions, FactoryOptions, HardhatEthersHelpers as HardhatEthersHelpersBase} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from "./index.js";

declare module "@nomicfoundation/hardhat-ethers/types" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
  getContractFactory(name: 'ConsentManager', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.ConsentManager__factory>
getContractFactory(name: 'Counter', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.Counter__factory>
getContractFactory(name: 'HealthConsent', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.HealthConsent__factory>
getContractFactory(name: 'IHealthConsent', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IHealthConsent__factory>
getContractFactory(name: 'IMedicalRecords', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IMedicalRecords__factory>
getContractFactory(name: 'MedicalRecordAccess', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MedicalRecordAccess__factory>
getContractFactory(name: 'IMedicalRecords', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IMedicalRecords__factory>
getContractFactory(name: 'MedicalRecordTransfer', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MedicalRecordTransfer__factory>
getContractFactory(name: 'IHealthConsent', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IHealthConsent__factory>
getContractFactory(name: 'MedicalRecords', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MedicalRecords__factory>
getContractFactory(name: 'IHealthConsent', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IHealthConsent__factory>
getContractFactory(name: 'RecordTransfer', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.RecordTransfer__factory>

  getContractAt(name: 'ConsentManager', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.ConsentManager>
getContractAt(name: 'Counter', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.Counter>
getContractAt(name: 'HealthConsent', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.HealthConsent>
getContractAt(name: 'IHealthConsent', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IHealthConsent>
getContractAt(name: 'IMedicalRecords', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IMedicalRecords>
getContractAt(name: 'MedicalRecordAccess', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MedicalRecordAccess>
getContractAt(name: 'IMedicalRecords', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IMedicalRecords>
getContractAt(name: 'MedicalRecordTransfer', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MedicalRecordTransfer>
getContractAt(name: 'IHealthConsent', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IHealthConsent>
getContractAt(name: 'MedicalRecords', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MedicalRecords>
getContractAt(name: 'IHealthConsent', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IHealthConsent>
getContractAt(name: 'RecordTransfer', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.RecordTransfer>

  deployContract(name: 'ConsentManager', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ConsentManager>
deployContract(name: 'Counter', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Counter>
deployContract(name: 'HealthConsent', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.HealthConsent>
deployContract(name: 'IHealthConsent', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IHealthConsent>
deployContract(name: 'IMedicalRecords', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IMedicalRecords>
deployContract(name: 'MedicalRecordAccess', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MedicalRecordAccess>
deployContract(name: 'IMedicalRecords', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IMedicalRecords>
deployContract(name: 'MedicalRecordTransfer', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MedicalRecordTransfer>
deployContract(name: 'IHealthConsent', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IHealthConsent>
deployContract(name: 'MedicalRecords', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MedicalRecords>
deployContract(name: 'IHealthConsent', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IHealthConsent>
deployContract(name: 'RecordTransfer', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.RecordTransfer>

  deployContract(name: 'ConsentManager', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ConsentManager>
deployContract(name: 'Counter', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Counter>
deployContract(name: 'HealthConsent', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.HealthConsent>
deployContract(name: 'IHealthConsent', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IHealthConsent>
deployContract(name: 'IMedicalRecords', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IMedicalRecords>
deployContract(name: 'MedicalRecordAccess', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MedicalRecordAccess>
deployContract(name: 'IMedicalRecords', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IMedicalRecords>
deployContract(name: 'MedicalRecordTransfer', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MedicalRecordTransfer>
deployContract(name: 'IHealthConsent', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IHealthConsent>
deployContract(name: 'MedicalRecords', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MedicalRecords>
deployContract(name: 'IHealthConsent', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IHealthConsent>
deployContract(name: 'RecordTransfer', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.RecordTransfer>

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
  