/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as consentSol from './Consent.sol/index.js';
export type { consentSol };
import type * as medicalRecordAccessSol from './MedicalRecordAccess.sol/index.js';
export type { medicalRecordAccessSol };
import type * as medicalRecordTransferSol from './MedicalRecordTransfer.sol/index.js';
export type { medicalRecordTransferSol };
import type * as medicalRecordsSol from './MedicalRecords.sol/index.js';
export type { medicalRecordsSol };
import type * as recordTransferSol from './RecordTransfer.sol/index.js';
export type { recordTransferSol };
export type { Counter } from './Counter.js';
export type { HealthConsent } from './HealthConsent.js';
export * as factories from './factories/index.js';
export type { ConsentManager } from './Consent.sol/ConsentManager.js';
export { ConsentManager__factory } from './factories/Consent.sol/ConsentManager__factory.js';
export { Counter__factory } from './factories/Counter__factory.js';
export { HealthConsent__factory } from './factories/HealthConsent__factory.js';
export type { IHealthConsent } from './MedicalRecordAccess.sol/IHealthConsent.js';
export { IHealthConsent__factory } from './factories/MedicalRecordAccess.sol/IHealthConsent__factory.js';
export type { IMedicalRecords } from './MedicalRecordAccess.sol/IMedicalRecords.js';
export { IMedicalRecords__factory } from './factories/MedicalRecordAccess.sol/IMedicalRecords__factory.js';
export type { MedicalRecordAccess } from './MedicalRecordAccess.sol/MedicalRecordAccess.js';
export { MedicalRecordAccess__factory } from './factories/MedicalRecordAccess.sol/MedicalRecordAccess__factory.js';
export type { MedicalRecordTransfer } from './MedicalRecordTransfer.sol/MedicalRecordTransfer.js';
export { MedicalRecordTransfer__factory } from './factories/MedicalRecordTransfer.sol/MedicalRecordTransfer__factory.js';
export type { MedicalRecords } from './MedicalRecords.sol/MedicalRecords.js';
export { MedicalRecords__factory } from './factories/MedicalRecords.sol/MedicalRecords__factory.js';
export type { RecordTransfer } from './RecordTransfer.sol/RecordTransfer.js';
export { RecordTransfer__factory } from './factories/RecordTransfer.sol/RecordTransfer__factory.js';