/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IHealthConsent__factory } from './IHealthConsent__factory.js';
export { IMedicalRecords__factory } from './IMedicalRecords__factory.js';
export { MedicalRecordAccess__factory } from './MedicalRecordAccess__factory.js';