/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IMedicalRecords } from './IMedicalRecords.js';
export type { MedicalRecordTransfer } from './MedicalRecordTransfer.js';