/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as consentSol from './Consent.sol/index.js';
export * as medicalRecordAccessSol from './MedicalRecordAccess.sol/index.js';
export * as medicalRecordTransferSol from './MedicalRecordTransfer.sol/index.js';
export * as medicalRecordsSol from './MedicalRecords.sol/index.js';
export * as recordTransferSol from './RecordTransfer.sol/index.js';
export { Counter__factory } from './Counter__factory.js';
export { HealthConsent__factory } from './HealthConsent__factory.js';