/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IHealthConsent } from './IHealthConsent.js';
export type { MedicalRecords } from './MedicalRecords.js';