/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IMedicalRecords, IMedicalRecordsInterface } from "../../RecordTransfer.sol/IMedicalRecords.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "_patient",
        "type": "address"
      }
    ],
    "name": "getRecords",
    "outputs": [
      {
        "internalType": "string[]",
        "name": "",
        "type": "string[]"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;

  export class IMedicalRecords__factory {
    static readonly abi = _abi;
    static createInterface(): IMedicalRecordsInterface {
      return new Interface(_abi) as IMedicalRecordsInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): IMedicalRecords {
      return new Contract(address, _abi, runner) as unknown as IMedicalRecords;
    }
  }
  