/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IHealthConsent__factory } from './IHealthConsent__factory.js';
export { RecordTransfer__factory } from './RecordTransfer__factory.js';