/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  
export declare namespace ConsentManager {
      
    export type ConsentStruct = {hasSigned: boolean, timestamp: BigNumberish, consentHash: string, ipfsCid: string}

    export type ConsentStructOutput = [hasSigned: boolean, timestamp: bigint, consentHash: string, ipfsCid: string] & {hasSigned: boolean, timestamp: bigint, consentHash: string, ipfsCid: string }
  
    }

  export interface ConsentManagerInterface extends Interface {
    getFunction(nameOrSignature: "getConsent" | "hasSignedConsent" | "signConsent"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "ConsentSigned"): EventFragment;

    encodeFunctionData(functionFragment: 'getConsent', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'hasSignedConsent', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'signConsent', values: [AddressLike, string, string]): string;

    decodeFunctionResult(functionFragment: 'getConsent', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hasSignedConsent', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'signConsent', data: BytesLike): Result;
  }

  
    export namespace ConsentSignedEvent {
      export type InputTuple = [patient: AddressLike, timestamp: BigNumberish, consentHash: string, ipfsCid: string];
      export type OutputTuple = [patient: string, timestamp: bigint, consentHash: string, ipfsCid: string];
      export interface OutputObject {patient: string, timestamp: bigint, consentHash: string, ipfsCid: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface ConsentManager extends BaseContract {
    
    connect(runner?: ContractRunner | null): ConsentManager;
    waitForDeployment(): Promise<this>;

    interface: ConsentManagerInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    getConsent: TypedContractMethod<
      [_patient: AddressLike, ],
      [ConsentManager.ConsentStructOutput[]],
      'view'
    >
    

    
    hasSignedConsent: TypedContractMethod<
      [_patient: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    signConsent: TypedContractMethod<
      [_patient: AddressLike, _consentHash: string, _ipfsCid: string, ],
      [boolean],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'getConsent'): TypedContractMethod<
      [_patient: AddressLike, ],
      [ConsentManager.ConsentStructOutput[]],
      'view'
    >;
getFunction(nameOrSignature: 'hasSignedConsent'): TypedContractMethod<
      [_patient: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'signConsent'): TypedContractMethod<
      [_patient: AddressLike, _consentHash: string, _ipfsCid: string, ],
      [boolean],
      'nonpayable'
    >;

    getEvent(key: 'ConsentSigned'): TypedContractEvent<ConsentSignedEvent.InputTuple, ConsentSignedEvent.OutputTuple, ConsentSignedEvent.OutputObject>;

    filters: {
      
      'ConsentSigned(address,uint256,string,string)': TypedContractEvent<ConsentSignedEvent.InputTuple, ConsentSignedEvent.OutputTuple, ConsentSignedEvent.OutputObject>;
      ConsentSigned: TypedContractEvent<ConsentSignedEvent.InputTuple, ConsentSignedEvent.OutputTuple, ConsentSignedEvent.OutputObject>;
    
    };
  }