/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IMedicalRecords__factory } from './IMedicalRecords__factory.js';
export { MedicalRecordTransfer__factory } from './MedicalRecordTransfer__factory.js';