/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BytesLike, FunctionFragment, Result, Interface, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface IMedicalRecordsInterface extends Interface {
    getFunction(nameOrSignature: "getKeyShare" | "getRecords" | "grantAccess"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'getKeyShare', values: [string]): string;
encodeFunctionData(functionFragment: 'getRecords', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'grantAccess', values: [AddressLike, string, BytesLike]): string;

    decodeFunctionResult(functionFragment: 'getKeyShare', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getRecords', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'grantAccess', data: BytesLike): Result;
  }

  

  export interface IMedicalRecords extends BaseContract {
    
    connect(runner?: ContractRunner | null): IMedicalRecords;
    waitForDeployment(): Promise<this>;

    interface: IMedicalRecordsInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    getKeyShare: TypedContractMethod<
      [_ipfsCid: string, ],
      [string],
      'view'
    >
    

    
    getRecords: TypedContractMethod<
      [_patient: AddressLike, ],
      [string[]],
      'view'
    >
    

    
    grantAccess: TypedContractMethod<
      [grantee: AddressLike, ipfsCid: string, encryptedKeyShare: BytesLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'getKeyShare'): TypedContractMethod<
      [_ipfsCid: string, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getRecords'): TypedContractMethod<
      [_patient: AddressLike, ],
      [string[]],
      'view'
    >;
getFunction(nameOrSignature: 'grantAccess'): TypedContractMethod<
      [grantee: AddressLike, ipfsCid: string, encryptedKeyShare: BytesLike, ],
      [void],
      'nonpayable'
    >;

    

    filters: {
      
    };
  }