/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IHealthConsent } from './IHealthConsent.js';
export type { IMedicalRecords } from './IMedicalRecords.js';
export type { MedicalRecordAccess } from './MedicalRecordAccess.js';